#####################################################################################################
#####  _____    ___    _              _   _    ______   __    __              _______   _____   #####
##### /  ___|  |   \  | |     /\     | | / /  |  ____| |  \  /  |     /\     /  _____| /  ___|  #####
##### | (___   | |\ \ | |    /  \    | |/ /   | |____  |   \/   |    /  \    | |   __  | (___   #####
#####  \___ \  | | \ \| |   / /\ \   | |\ \   |  ____| | |\  /| |   / /\ \   | |  |_ |  \___ \  #####
#####  ____) | | |  \   |  / /__\ \  | | \ \  | |____  | | \/ | |  / /__\ \  | |____||  ____) | #####
##### |_____/  |_|   \__| /_/    \_\ |_|  \_\ |______| |_|    |_| /_/    \_\  \______/ |_____/  #####
#####                                                                                           #####
#####################################################################################################

############################
### Execution parameters ###
############################

working_dir: /path/to/working/directory/                                 #The main directory for the project
raw_fastq: /path/to/raw_fastq/                                           #The directory that contains all the fastq files of all the samples (eg. sample1_R1.fastq & sample1_R2.fastq, sample2_R1.fastq & sample2_R2.fastq...)
suffix_1: "_R1.fastq"                                                    #Main type of suffix for forward reads file (eg. _1.fastq or _R1.fastq or _r1.fastq or _1.fq or _R1.fq or _r1.fq )
suffix_2: "_R2.fastq"                                                    #Main type of suffix for reverse reads file (eg. _2.fastq or _R2.fastq or _r2.fastq or _2.fq or _R2.fq or _r2.fq )

###########################
### Conda environnemnts ###
###########################

conda_env: "/path/to/SnakeMAGs_conda_env/"

#########################
### Quality filtering ###
#########################
email: name.surname@your-univ.com                                        #Your e-mail address
threads_filter: 10                                                       #The number of threads to run this process. To be adjusted according to your hardware
resources_filter: 150                                                    #Memory according to tools need (in GB)

########################
### Adapter trimming ###
########################
adapters: /path/to/working/directory/adapters.fa                         #A fasta file containing a set of various Illumina adaptors (this file is provided and is also available on github)
trim_params: "2:40:15"                                                   #For further details, see the Trimmomatic documentation
threads_trim: 10                                                         #The number of threads to run this process. To be adjusted according to your hardware
resources_trim: 150                                                      #Memory according to tools need (in GB)

######################
### Host filtering ###
######################
host_genome: "yes"                                                       #yes or no. An optional step for host-associated samples (eg. termite, human, plant...)
threads_bowtie2: 50                                                      #The number of threads to run this process. To be adjusted according to your hardware
host_genomes_directory: /path/to/working/host_genomes/                   #the directory where the host genome is stored
host_genomes: /path/to/working/host_genomes/host_genomes.fa              #A fasta file containing the DNA sequences of the host genome(s)
threads_samtools: 50                                                     #The number of threads to run this process. To be adjusted according to your hardware
resources_host_filtering: 150                                            #Memory according to tools need (in GB)

################
### Assembly ###
################
threads_megahit: 50                                                      #The number of threads to run this process. To be adjusted according to your hardware
min_contig_len: 1000                                                     #Minimum length (in bp) of the assembled contigs
k_list: "21,31,41,51,61,71,81,91,99,109,119"                             #Kmer size (for further details, see the megahit documentation)
resources_megahit: 250                                                   #Memory according to tools need (in GB)

###############
### Binning ###
###############
threads_bwa: 50                                                          #The number of threads to run this process. To be adjusted according to your hardware
resources_bwa: 250                                                       #Memory according to tools need (in GB)
threads_samtools: 50                                                     #The number of threads to run this process. To be adjusted according to your hardware
resources_samtools: 150                                                  #Memory according to tools need (in GB)
seed: 19860615                                                           #Seed number for reproducible results
threads_metabat: 50                                                      #The number of threads to run this process. To be adjusted according to your hardware
minContig: 2500                                                          #Minimum length (in bp) of the contigs
resources_binning: 250                                                   #Memory according to tools need (in GB)

####################
### Bins quality ###
####################
#checkM
threads_checkm: 50                                                       #The number of threads to run this process. To be adjusted according to your hardware
resources_checkm: 250                                                    #Memory according to tools need (in GB)

#bins_quality_filtering
completion: 50                                                           #The minimum completion rate of bins
contamination: 10                                                        #The maximum contamination rate of bins
parks_quality_score: "no"                                                #yes or no. If yes bins are filtered according to the Parks quality score (completion-5*contamination >= 50)

#GUNC
gunc: "yes"                                                              #yes (recommended) or no. An optional step to detect and discard chimeric and contaminated genomes using the GUNC tool
threads_gunc: 50                                                         #The number of threads to run this process. To be adjusted according to your hardware
resources_gunc: 250                                                      #Memory according to tools need (in GB)
GUNC_db: /path/to/GUNC_DB/gunc_db_progenomes2.1.dmnd                     #Path to the downloaded GUNC database (see the readme file)

######################
### Classification ###
######################
GTDB_data_ref: /path/to/downloaded/GTDB                                  #Path to uncompressed GTDB-Tk reference data (GTDB)
threads_gtdb: 10                                                         #The number of threads to run this process. To be adjusted according to your hardware
resources_gtdb: 250                                                      #Memory according to tools need (in GB)

##################
### Abundances ###
##################
threads_coverM: 10                                                       #The number of threads to run this process. To be adjusted according to your hardware
resources_coverM: 150                                                    #Memory according to tools need (in GB)
